version: "3.5"
services:
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/gotham_dev
    depends_on:
      - db
    ports:
      - "4000:4000"
    command: bash -c "mix deps.get && mix ecto.create && mix ecto.migrate && mix phx.server"

  db:
    image: postgres:14-alpine
    command: 'postgres -c "max_connections=200"'
    environment:
      POSTGRES_PASSWORD: postgres

    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
volumes:
  postgres-data:
  deps:
  build: