version: "3.5"
services:
  backend:
    build: ./backend
    container_name: gotham_backend
    environment:
      MIX_ENV: dev
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - gotham_network

  db:
    image: postgres:14-alpine
    container_name: gotham_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres
    networks:
      - gotham_network

networks:
  gotham_network:

volumes:
  db: