name: Build Test And Deploy
on:
  push:
    branches:
      - master
jobs:
  ci-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

  ci-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test

  deploy:
    needs: [ ci-backend, ci-frontend ]
    runs-on: self-hosted
    steps:
      - run: sudo rm -rf "/home/ubuntu/actions-runner/_work/Gotham/Gotham/backend"
      - uses: actions/checkout@v2
      - run: sed -e "s/API_URL=.*/API_URL=http:\/\/51.68.70.219:4000/g" -i ./frontend/.env
      - run: docker-compose down -v && docker-compose up --build -d backend
      - run: cd frontend && npm install && npm run build && rm -rf /var/www/html/. && cp -r ./dist /var/www/html
      - run: sudo systemctl restart apache2